kind: pipeline
name: RAD KERNEL BUILD OLDCAM

clone:
  disable: true

steps:
- name: oldcam
  image: archlinux:latest
  environment:
      TG_BOT_API:
        from_secret: TG_BOT_API
  commands:
    - "export TG_BOT_API"
    - pacman -Sy base-devel bc llvm curl zip wget git --noconfirm
    - git clone --depth=1 --quiet https://github.com/Team-420/Nethunter-Whyred-Eas.git -b kernel-eas source
    - cd source
    - git clone --depth=1 --quiet https://github.com/theradcolor/lazyscripts.git -b master
    - sed -i "s/token=.*/token=$TG_BOT_API/g" lazyscripts/ci-scripts/ci-rad
    - script -c "bash -x build.sh --oldcam" build.log

---
kind: pipeline
name: RAD KERNEL BUILD NEWCAM

clone:
  disable: true

steps:
- name: newcam
  image: archlinux:latest
  environment:
      TG_BOT_API:
        from_secret: TG_BOT_API
  commands:
    - "export TG_BOT_API"
    - pacman -Sy base-devel bc llvm curl zip wget git --noconfirm
    - git clone --depth=1 --quiet https://github.com/Team-420/Nethunter-Whyred-Eas.git -b kernel-eas source
    - cd source
    - git clone --depth=1 --quiet https://github.com/theradcolor/lazyscripts.git -b master
    - sed -i "s/token=.*/token=$TG_BOT_API/g" lazyscripts/ci-scripts/ci-rad
    - script -c "bash -x build.sh --newcam" build.log
